<%@ page contentType="text/html;charset=utf-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport"
  content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="keywords" content="同方,在线教育,同方凌讯">
<title>同方教育在线 - 我的学习轨迹</title>
<link type="text/css" rel="stylesheet"
  href="./bootstrap/css/bootstrap.min.css" />
<link type="text/css" rel="stylesheet" href="./css/base.css" />
<link type="text/css" rel="stylesheet" href="./css/calendar.css" />
<link type="text/css" rel="stylesheet" href="./css/my.css" />
<script type="text/javascript" src="./bootstrap/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="./js/common.js"></script>
</head>
<body>
  <div id="top"></div>
  
    <nav class="navbar">
    <div class="container-fluid">
    <a class="navbar-brand" href="index.jsp">
      <img class="logo" src="./images/logo.jpg" title="同方教育在线" />
    </a>
      <div id="navbar" class="navbar-collapse collapse">
        <jsp:include page="./include/nav.jsp" flush="true" />
        <jsp:include page="./include/nav-right.jsp" flush="true" />
      </div>
           <%
          if (null == session) {
            out.print("<script>location.href='login.jsp?referer=mytrack.jsp'</script>");
          }
        %>
      <!--/.navbar-collapse -->
    </div>
  </nav>

  <div class="mywrapper">
    <div class="home-crumb">
      <span><a href="index.jsp">首页</a></span> <span class="crumb-arrow"><a
        href="model-school.jsp">我的示范校</a></span> <span class="crumb-arrow">学习中心</span>
    </div>
    <div class="main-wrapper">
      <div class="nav-cont" id="js_navcont">

      </div>
      <!-- calendar -->
      <div class="main-cont">
        <div class="panel user-track">
          <article class="content">
            <section class="thuimg">
              <!--<script type="text/javascript" src="./js/thuimg.js"></script>-->
              <!-- 海报图 / swf动画 -->
              <div class="thuimgWrap" id="thuimgWrap">
                <a class="thuimga thua" href=""> <img
                  class="mainImg" src="" data-date="" title="学习日记与大事件">
                </a>
              </div>
              <!-- 图片字幕 + 日期轴 -->
              <section class="mainWrap relative">
                <!-- 轮播图 prev -->
                <a class="imgarrow imgarrowleft" id="thuimgPre"> <img
                  src="./images/svg/arrowleft.svg" />
                </a>
                <!-- 轮播图 next -->
                <a class="imgarrow imgarrowright" id="thuimgNext"
                  style="display: block;"> <img
                  src="./images/svg/arrowright.svg" />
                </a>
                <!-- 图片字幕 -->
                <div class="imgTitle">
                  <span class="bg"></span> <a class="txt yahei thua"
                    id="thuImgTitle" href=""></a> <span class="day"
                    id="calendarToday"> <!--2017.8.14-->
                  </span>
                </div>
                <!-- 日期轴 -->
                <div class="month clearfix">
                  <a class="arrowleft arrow" id="calendarMonthpre"><span></span></a>
                  <a class="arrowright arrow" id="calendarMonthnext"><span></span></a>
                  <div class="monthTxt">
                    <span id="calendarYear" class="hide">2017</span> <span
                      id="calendarMonth">8</span>月
                  </div>
                  <ul class="day clearfix" id="calendarDay">
                    <!-- Generated by @file: index.js @function: Calendar() -->
                  </ul>
                </div>
              </section>
            </section>
          </article>
          <form id="user-track-form" class="form-horizontal"
            method="POST" enctype="multipart/form-data">
            <input id="js-eventid" type="hidden" name="id"> <input
              type="hidden" name="userid"
              value="<%=session.getAttribute("userid")%>">
            <div class="form-group">
              <label class="col-md-1 control-label" for="track-theme">主题:</label>
              <div class="col-md-5 controls radios">
                <input type="text" id="track-theme" name="title"
                  class="form-control" value="">
                <div class="help-block" style="display: none;"></div>
              </div>
              <label class="col-md-1 control-label" for="track-date">日期:</label>
              <div class="col-md-2 controls radios">
                <input id="track-date" class="form-control" type="text"
                  name="createDate" readonly />
                <div class="help-block" style="display: none;"></div>
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-1 control-label" for="track-text">正文:</label>
              <div class="col-md-8 controls radios">
                <textarea id="track-text" name="content" class="form-control" rows="5"></textarea>
                <div class="help-block" style="display: none;"></div>
              </div>
              <div class="col-md-3" id="js-preview"
                class="image-preview" title="图片上传预览"></div>
            </div>
            <div class="row">
              <div class="col-sm-2 col-sm-offset-1">
                <button id="track-save-btn" data-submiting-text="正在保存"
                  type="submit" class="btn btn-primary">
                  <span class="glyphicon glyphicon-floppy-save"></span>保存
                </button>
              </div>
              <div class="col-sm-2">
                <label for="track-upload" class="btn btn-primary"><span
                  class="glyphicon glyphicon-picture"></span>上传图片</label> <input
                  id="track-upload" type="file" class="hide"
                  name="imageFile" />
              </div>
              <!-- <div class="col-sm-2"><button class="btn btn-danger"><span class="glyphicon glyphicon-trash">删除</span></button></div> -->
            </div>
          </form>

        </div>
        <!-- /.panel.user-track -->
      </div>
      <!-- /.main-cont -->
    </div>

  </div>
  <div id="footer"></div>         
  <script>$("#footer").load("./include/footer.html");</script>
  <script type="text/javascript" src="./js/my.js"></script>
  <script type="text/javascript" src="./js/calendar.js"></script>
  <script type="text/javascript" src="./js/mytrack.js"></script>
</body>
</html>